on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

jobs:
  ci-linux:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now, MSRV is 1.75.0
        rust: [nightly, stable, 1.75.0]

        include:
          # Nightly is only for reference and allowed to fail
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run CI script for x86_64-unknown-linux-gnu
        run: |
          cargo check
      - name: Run tests
        run: |
          cargo test

  # On macOS and Windows, we at least make sure that the crate builds and links.
  build-other:
    strategy:
      matrix:
        os:
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build crate for host OS
        run: |
          cargo build
      - name: Test on host OS
        run: |
          cargo test

  build-example-parallel-ili9341-rp-pico:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
      - run: cargo install flip-link
      - name: Build example
        run: cargo build
        working-directory: ./mipidsi/examples/parallel_ili9341_rp_pico
